// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV572KmRD9BUmWNSx7-jEkTfvOn0fYxuk',
    appId: '1:257009473607:web:9bd2e5f02d43a0781df962',
    messagingSenderId: '257009473607',
    projectId: 'loginsignup-8c0a2',
    authDomain: 'loginsignup-8c0a2.firebaseapp.com',
    storageBucket: 'loginsignup-8c0a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClN_jfTnfOeatniuQn4EjrT9Ngiv0HhCE',
    appId: '1:257009473607:android:e9e62a4a81add7d01df962',
    messagingSenderId: '257009473607',
    projectId: 'loginsignup-8c0a2',
    storageBucket: 'loginsignup-8c0a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxTwG9dJ3BJ2WDCT-ESwzfdFYtkHim7oM',
    appId: '1:257009473607:ios:947e3e2212fbe9b81df962',
    messagingSenderId: '257009473607',
    projectId: 'loginsignup-8c0a2',
    storageBucket: 'loginsignup-8c0a2.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxTwG9dJ3BJ2WDCT-ESwzfdFYtkHim7oM',
    appId: '1:257009473607:ios:ee816330ceb088191df962',
    messagingSenderId: '257009473607',
    projectId: 'loginsignup-8c0a2',
    storageBucket: 'loginsignup-8c0a2.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
